version: '3.3'
services:
 # db container
  db:
    image: postgres:14.0
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  # backend container
  backend:
    image: eltimccc/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/static/
      - media_value:/media/
    depends_on:
      - db
    env_file:
      - ./.env
  # frontend container
  frontend:
    image: eltimccc/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

volumes:
  static_value:
  media_value:
  db_value: