# Generated by Django 3.2.13 on 2022-11-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_ingredients"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ingredients",
            new_name="Ingredient",
        ),
    ]
