# Generated by Django 3.2.13 on 2022-11-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_auto_20221114_1105"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-id",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
    ]
